### ISSUE TITLE
Add in usable JS events.

### ISSUE THREAD

**Issue by danieliser** [easydigitaldownloads/gravity-forms-help-scout-search#11]
Adding in some JS events would be super helpful. For instance when search starts, when results are found, when list is rendered etc.

These can be used to further customize the interaction that occurs such as loading animations and do not require any real work to add :).

**Comment by pippinsplugins** [comment]
PR submitted.

**Comment by pippinsplugins** [comment]
@sumobi mind taking a look?

**Comment by pippinsplugins** [comment]
Oops, wrong issue for the PR. Oh well :)

**Comment by pippinsplugins** [comment]
Done.

**Comment by danieliser** [comment]
Awesome, thanks for that. Perfect timing yet again.
