### ISSUE TITLE
Open Support Ticket button appears too soon

### ISSUE THREAD

**Issue by SeanChDavis** [easydigitaldownloads/gravity-forms-help-scout-search#16]
When entering a search term, the button for opening a support ticket appears on the screen before the search results do. Obviously, some people are going to chase the button down and skip over the search results.

**Comment by pippinsplugins** [comment]
I'm going to go ahead and just make the decision that the submit button should _always_ be hidden until the search is complete. That's how everyone is going to want it frankly, not just us at EDD.

**Comment by SeanChDavis** [comment]
That's honestly how I thought it was supposed to be. So I agree.
