### ISSUE TITLE
search results links using doc content as title attribute value

### ISSUE THREAD

**Issue by SeanChDavis** [easydigitaldownloads/gravity-forms-help-scout-search#17]
https://github.com/easydigitaldownloads/gravity-forms-help-scout-search/blob/master/gravity-forms-help-scout-search.php#L121

Using a `{preview}` of the doc content as the title attribute's value for the search results links can lead to some unexpected behavior depending on what's in the content. Here's what happened on AffiliateWP:

![slack-imgs com](https://cloud.githubusercontent.com/assets/2359131/16671889/265c23c2-4457-11e6-93b3-70db57439d41.png)

The title's value should probably be changed to `{name}`.

**Comment by SeanChDavis** [comment]
Well, my change is producing some strange results for me. No idea why: 

![2016-07-07 at 3 44 pm](https://cloud.githubusercontent.com/assets/2359131/16672268/dbbac7ee-4459-11e6-96d8-835e573f6983.png)

That's local. Can't get `{name}` to work there. The URLs are still correct. Any clue why, @pippinsplugins?

**Comment by pippinsplugins** [comment]
@SDavisMedia I think it may be `title` not `name`.

**Comment by SeanChDavis** [comment]
@pippinsplugins Super strange. That fixes the displayed text (which should have never been affected to begin with) but now using `{title}` is output as-is:

![screen shot 2016-07-07 at 8 57 58 pm](https://cloud.githubusercontent.com/assets/2359131/16677020/cb9a273e-4485-11e6-87c4-8ab35438dc20.png)

Gonna see if I can find some documentation on this.

**Comment by zackkatz** [comment]
What about fixing the HTML entity encoding for the `{preview}` text instead? I don't see any added value of adding a `title` attribute that is the same as the anchor text. I'd prefer just removing the `title` attribute instead.

Thoughts?

**Comment by zackkatz** [comment]
@SDavisMedia You're right that it should be `{name}`. The issue was that `.replace()` only replaces one instance of the found string. Fixed in this commit: https://github.com/easydigitaldownloads/gravity-forms-help-scout-search/commit/d4b0d607ed8b5e7b2813b21ff2dd71cfb3d14079

Would using the `gf_helpscout_docs_script_settings` filter work for you?
