### ISSUE TITLE
styles() method's CSS being outputted on every page

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/gravity-forms-help-scout-search#21]
As per the comment here (https://github.com/easydigitaldownloads/gravity-forms-help-scout-search/blob/master/gravity-forms-help-scout-search.php#L147) the `styles()` method should only be loaded on the preview page. It seems to be loaded on the front-end where ever a Gravity form is added.

It would be nice if these styles are only loaded on the admin preview page, or if they are supposed to be on the front-end, load them only on a page which contains a form which uses this plugin.

**Comment by zackkatz** [comment]
This is fixed in the develop branch. 

https://github.com/easydigitaldownloads/gravity-forms-help-scout-search/blob/develop/gravity-forms-help-scout-search.php#L168-L170
