### ISSUE TITLE
Update plugin information

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/gravity-forms-help-scout-search#27]
We should update the following:
- plugin author (Sandhills)
- tested to version (WP)
- donate link (currently 404)
- contributors

Not including the plugin URI here as that is a real page on @pippinsplugins site and is not on our site, but we could change the plugin URI to the WordPress repository as one option if that's desired.

**Comment by LisaCee** [comment]
PR #28 Updates this information
