### ISSUE TITLE
Ajax search does not work if you click to go back

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/gravity-forms-help-scout-search#6]
I've split the form up onto 2 pages and I'm using conditional logic to show the paging once the search field isn't empty. When first entering a search term the results show fine. But after going to the second page and clicking "back" the ajax search no longer works.

![screen recording 2016-06-29 at 11 01 am](https://cloud.githubusercontent.com/assets/52581/16435315/2eb5fb66-3de9-11e6-8211-bb0632b37d49.gif)

**Comment by amdrew** [comment]
Looks like the `docs-search-wrap` div isn't present in the HTML source when going back to the first page.

**Comment by zackkatz** [comment]
Nice catch, @sumobi

**Comment by amdrew** [comment]
@zackkatz works great now!

**Comment by amdrew** [comment]
@zackkatz just spotted a small issue on issue/6. The text shows twice when searching:

![screen shot 2016-06-29 at 12 42 27 pm](https://cloud.githubusercontent.com/assets/52581/16437009/12b715cc-3df7-11e6-93ae-58307a5d5dea.png)

**Comment by pippinsplugins** [comment]
@sumobi I can't replicate that.

**Comment by pippinsplugins** [comment]
Deployed to .org.
