### ISSUE TITLE
Duplicate content if more than 1 gravity form exists

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/gravity-forms-help-scout-search#8]
Related: https://github.com/easydigitaldownloads/gravity-forms-help-scout-search/issues/6#issuecomment-229225720

If there's another Gravity Form on the same page it runs more than once, and outputs duplicate search results/text. You can see this on our AffiliateWP support form now (clear browser cache) since we have an email signup in the site footer: https://affiliatewp.com/support/

![screen shot 2016-06-30 at 10 41 35 am](https://cloud.githubusercontent.com/assets/52581/16471281/b8196a3e-3eaf-11e6-857f-41cb1384b32d.png)

**Comment by amdrew** [comment]
I've just rolled back to v3.0 on AffiliateWP so you will no longer see the issue. To replicate, add another Gravity Form to the page somewhere and you will get duplicate results.

**Comment by pippinsplugins** [comment]
Why are there two forms on the same page?

**Comment by amdrew** [comment]
@pippinsplugins we have a signup form in the footer of the site. It's also likely other users could have another form somewhere on their page.

![screen shot 2016-07-01 at 11 20 28 am](https://cloud.githubusercontent.com/assets/52581/16507435/d9512e48-3f7d-11e6-919e-9d96f29bd198.png)

I've since removed it from the support page though because even though I rolled back to the previous version, it was still showing duplicate results (even after clearing cache).

**Comment by zackkatz** [comment]
@sumobi Can you test this and see if it works for you?

**Comment by amdrew** [comment]
@zackkatz super delayed response, yes that works :)

**Comment by SeanChDavis** [comment]
@zackkatz I just ran into the same issue working on EDD's site. I tested `issue/8` and it appears to be working perfectly for me. I don't see any undesirable side effects. I'm gonna just download and install the branch so I can move forward, but I'd say this is safe to merge.
