### ISSUE TITLE
Possible to bypass the search results with "enter" key

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/gravity-forms-help-scout-search#9]
It's possible to bypass the search results and land on the support form by typing something and then pressing "enter". This defeats the purpose of customers looking at the search results first before opening a ticket.

I think we should block the enter key.

**Comment by pippinsplugins** [comment]
Not really a problem, actually, just mark the field as required. That fixes it.

**Comment by pippinsplugins** [comment]
Nvm, yes it is. Missed the whole "enter something".

**Comment by pippinsplugins** [comment]
@sumobi try that out?

**Comment by amdrew** [comment]
@pippinsplugins That fixes the return/enter key from being used **before** the ajax results are shown, but as soon as the results appear, the enter key progresses to the next page of the form. Is that something we would fix in this plugin? Ideally the enter/return key would not work at all so the user is forced to at least see the results, then click to go to the next page.

**Comment by pippinsplugins** [comment]
I'll try and fix that too.

**Comment by pippinsplugins** [comment]
Fixed.

**Comment by amdrew** [comment]
Works great 👍
